const recipesData = [
    // Biryani and Pulao Recipes
    {
      id: '1',
      name: 'Chicken Biryani',
      chef: 'Chef Mehboob Khan',
      image: require('../assets/Chicken Biryani1.jpg'),
      description: 'A flavorful and aromatic rice dish made with basmati rice, chicken, and a blend of spices.',
      ingredients: [
        'Chicken - 1 kg',
        'Basmati rice - 500g',
        'Onions - 3 (sliced)',
        'Tomatoes - 4 (chopped)',
        'Yogurt - 1 cup',
        'Ginger-garlic paste - 2 tbsp',
        'Spices (cinnamon, cardamom, cloves, bay leaves)',
        'Fresh coriander and mint leaves - for garnish',
      ],
      method: [
        'Marinate chicken with yogurt, ginger-garlic paste, and spices for 1 hour.',
        'Cook basmati rice until 70% done and set aside.',
        'Fry onions until golden brown and set aside.',
        'In a pot, layer the marinated chicken, fried onions, and partially cooked rice.',
        'Cover and cook on low heat for 20-25 minutes.',
        'Garnish with fresh coriander and mint leaves before serving.',
      ],
    },
    {
      id: '2',
      name: 'Mutton Pulao',
      chef: 'Chef Rida Aftab',
      image: require('../assets/Mutton Pulao1.jpg'),
      description: 'A rich and hearty rice dish made with tender mutton and aromatic spices.',
      ingredients: [
        'Mutton - 1 kg',
        'Basmati rice - 500g',
        'Onions - 2 (sliced)',
        'Tomatoes - 3 (chopped)',
        'Ginger-garlic paste - 2 tbsp',
        'Spices (cumin, coriander, turmeric, garam masala)',
        'Fresh coriander leaves - for garnish',
      ],
      method: [
        'Cook mutton with ginger-garlic paste and spices until tender.',
        'Fry onions until golden brown and add tomatoes.',
        'Add cooked mutton and mix well.',
        'Add soaked basmati rice and water, then cook until rice is done.',
        'Garnish with fresh coriander leaves and serve hot.',
      ],
    },
    {
      id: '3',
      name: 'Sindhi Biryani',
      chef: 'Chef Zubaida Tariq',
      image: require('../assets/Sindhi Biryani.jpg'),
      description: 'A traditional Sindhi-style biryani with a unique blend of spices and potatoes.',
      ingredients: [
        'Chicken - 1 kg',
        'Basmati rice - 500g',
        'Potatoes - 3 (peeled and quartered)',
        'Yogurt - 1 cup',
        'Spices (cumin, coriander, turmeric, red chili powder)',
        'Fresh mint and coriander leaves - for garnish',
      ],
      method: [
        'Marinate chicken with yogurt and spices for 1 hour.',
        'Fry potatoes until golden brown and set aside.',
        'Layer marinated chicken, fried potatoes, and partially cooked rice in a pot.',
        'Cover and cook on low heat for 20-25 minutes.',
        'Garnish with fresh mint and coriander leaves before serving.',
      ],
    },
    {
      id: '4',
      name: 'Matar Pulao',
      chef: 'Chef Saadat Siddiqui',
      image: require('../assets/Matar Pulao.jpg'),
      description: 'A simple and delicious rice dish made with peas and aromatic spices.',
      ingredients: [
        'Basmati rice - 500g',
        'Green peas - 1 cup',
        'Onions - 2 (sliced)',
        'Ginger-garlic paste - 1 tbsp',
        'Spices (cumin, bay leaves, cinnamon)',
        'Fresh coriander leaves - for garnish',
      ],
      method: [
        'Fry onions until golden brown and add ginger-garlic paste.',
        'Add green peas and spices, then sauté for 2-3 minutes.',
        'Add soaked basmati rice and water, then cook until rice is done.',
        'Garnish with fresh coriander leaves and serve hot.',
      ],
    },
    {
      id: '5',
      name: 'Beef Biryani',
      chef: 'Chef Gulzar',
      image: require('../assets/Beef Biryani.jpg'),
      description: 'A flavorful biryani made with tender beef and aromatic spices.',
      ingredients: [
        'Beef - 1 kg',
        'Basmati rice - 500g',
        'Onions - 3 (sliced)',
        'Tomatoes - 4 (chopped)',
        'Yogurt - 1 cup',
        'Spices (cinnamon, cardamom, cloves, bay leaves)',
        'Fresh coriander and mint leaves - for garnish',
      ],
      method: [
        'Marinate beef with yogurt, ginger-garlic paste, and spices for 1 hour.',
        'Cook basmati rice until 70% done and set aside.',
        'Fry onions until golden brown and set aside.',
        'In a pot, layer the marinated beef, fried onions, and partially cooked rice.',
        'Cover and cook on low heat for 20-25 minutes.',
        'Garnish with fresh coriander and mint leaves before serving.',
      ],
    },
    {
      id: '6',
      name: 'Yakhni Pulao',
      chef: 'Chef Tahir Chaudhry',
      image: require('../assets/Yakhni Pulao.jpg'),
      description: 'A fragrant rice dish made with meat stock and aromatic spices.',
      ingredients: [
        'Mutton - 1 kg',
        'Basmati rice - 500g',
        'Onions - 2 (sliced)',
        'Ginger-garlic paste - 2 tbsp',
        'Spices (cumin, coriander, turmeric, garam masala)',
        'Fresh coriander leaves - for garnish',
      ],
      method: [
        'Cook mutton with ginger-garlic paste and spices until tender.',
        'Strain the stock and set aside.',
        'Fry onions until golden brown and add cooked mutton.',
        'Add soaked basmati rice and stock, then cook until rice is done.',
        'Garnish with fresh coriander leaves and serve hot.',
      ],
    },
    {
      id: '7',
      name: 'Tikka Biryani',
      chef: 'Chef Naheed Ansari',
      image: require('../assets/Tikka Biryani.webp'),
      description: 'A spicy biryani made with marinated chicken tikka and aromatic rice.',
      ingredients: [
        'Chicken tikka - 1 kg',
        'Basmati rice - 500g',
        'Onions - 3 (sliced)',
        'Tomatoes - 4 (chopped)',
        'Yogurt - 1 cup',
        'Spices (cumin, coriander, turmeric, red chili powder)',
        'Fresh coriander and mint leaves - for garnish',
      ],
      method: [
        'Marinate chicken tikka with yogurt and spices for 1 hour.',
        'Cook basmati rice until 70% done and set aside.',
        'Fry onions until golden brown and set aside.',
        'In a pot, layer the marinated chicken tikka, fried onions, and partially cooked rice.',
        'Cover and cook on low heat for 20-25 minutes.',
        'Garnish with fresh coriander and mint leaves before serving.',
      ],
    },
    {
      id: '8',
      name: 'Vegetable Pulao',
      chef: 'Chef Asad Latif',
      image: require('../assets/Vegetable Pulao.jpg'),
      description: 'A healthy and flavorful rice dish made with mixed vegetables.',
      ingredients: [
        'Basmati rice - 500g',
        'Mixed vegetables (carrots, peas, beans) - 2 cups',
        'Onions - 2 (sliced)',
        'Ginger-garlic paste - 1 tbsp',
        'Spices (cumin, bay leaves, cinnamon)',
        'Fresh coriander leaves - for garnish',
      ],
      method: [
        'Fry onions until golden brown and add ginger-garlic paste.',
        'Add mixed vegetables and spices, then sauté for 2-3 minutes.',
        'Add soaked basmati rice and water, then cook until rice is done.',
        'Garnish with fresh coriander leaves and serve hot.',
      ],
    },
    {
      id: '9',
      name: 'Hyderabadi Biryani',
      chef: 'Chef Rahat',
      image: require('../assets/Hyderabadi Biryani.jpg'),
      description: 'A classic Hyderabadi-style biryani with layers of marinated meat and rice.',
      ingredients: [
        'Chicken - 1 kg',
        'Basmati rice - 500g',
        'Onions - 3 (sliced)',
        'Tomatoes - 4 (chopped)',
        'Yogurt - 1 cup',
        'Spices (cinnamon, cardamom, cloves, bay leaves)',
        'Fresh coriander and mint leaves - for garnish',
      ],
      method: [
        'Marinate chicken with yogurt, ginger-garlic paste, and spices for 1 hour.',
        'Cook basmati rice until 70% done and set aside.',
        'Fry onions until golden brown and set aside.',
        'In a pot, layer the marinated chicken, fried onions, and partially cooked rice.',
        'Cover and cook on low heat for 20-25 minutes.',
        'Garnish with fresh coriander and mint leaves before serving.',
      ],
    },
    {
      id: '10',
      name: 'Masoor Dal Pulao',
      chef: 'Chef Samina Jalil',
      image: require('../assets/Masoor Dal Pulao.jpeg'),
      description: 'A nutritious rice dish made with red lentils and aromatic spices.',
      ingredients: [
        'Basmati rice - 500g',
        'Masoor dal (red lentils) - 1 cup',
        'Onions - 2 (sliced)',
        'Ginger-garlic paste - 1 tbsp',
        'Spices (cumin, bay leaves, cinnamon)',
        'Fresh coriander leaves - for garnish',
      ],
      method: [
        'Cook masoor dal until soft and set aside.',
        'Fry onions until golden brown and add ginger-garlic paste.',
        'Add cooked masoor dal and spices, then sauté for 2-3 minutes.',
        'Add soaked basmati rice and water, then cook until rice is done.',
        'Garnish with fresh coriander leaves and serve hot.',
      ],
    },
  
    // Chicken Recipes
    {
      id: '11',
      name: 'Chicken Karahi',
      chef: 'Chef Shireen Anwar',
      image: require('../assets/11.jpg'),
      description: 'A spicy and flavorful Pakistani chicken dish cooked in a karahi (wok).',
      ingredients: [
        'Chicken - 1 kg',
        'Tomatoes - 4 (chopped)',
        'Green chilies - 4 (slit)',
        'Ginger-garlic paste - 2 tbsp',
        'Yogurt - 1/2 cup',
        'Spices (red chili powder, turmeric, cumin, coriander)',
        'Fresh coriander leaves - for garnish',
      ],
      method: [
        'Heat oil in a karahi and add ginger-garlic paste.',
        'Add chicken and cook until it changes color.',
        'Add tomatoes, green chilies, and spices. Cook until tomatoes are soft.',
        'Add yogurt and cook until the oil separates.',
        'Garnish with fresh coriander leaves and serve hot.',
      ],
    },
    {
      id: '12',
      name: 'Butter Chicken',
      chef: 'Chef Mehboob Khan',
      image: require('../assets/Butter Chicken1.jpg'),
      description: 'A creamy and rich Indian chicken dish made with tomato sauce and butter.',
      ingredients: [
        'Chicken - 1 kg',
        'Tomatoes - 6 (pureed)',
        'Butter - 4 tbsp',
        'Cream - 1 cup',
        'Ginger-garlic paste - 2 tbsp',
        'Spices (turmeric, red chili powder, garam masala)',
        'Fresh coriander leaves - for garnish',
      ],
      method: [
        'Marinate chicken with yogurt, ginger-garlic paste, and spices for 1 hour.',
        'Grill or fry the chicken until cooked.',
        'In a pan, melt butter and add tomato puree. Cook until oil separates.',
        'Add grilled chicken and cream. Simmer for 10 minutes.',
        'Garnish with fresh coriander leaves and serve hot.',
      ],
    },
    {
      id: '13',
      name: 'Chicken Handi',
      chef: 'Chef Zubaida Tariq',
      image: require('../assets/13.jpg'),
      description: 'A creamy and spicy chicken dish cooked in a traditional handi (clay pot).',
      ingredients: [
        'Chicken - 1 kg',
        'Tomatoes - 4 (chopped)',
        'Onions - 2 (sliced)',
        'Ginger-garlic paste - 2 tbsp',
        'Cream - 1 cup',
        'Spices (turmeric, red chili powder, garam masala)',
        'Fresh coriander leaves - for garnish',
      ],
      method: [
        'Heat oil in a handi and fry onions until golden brown.',
        'Add ginger-garlic paste and chicken. Cook until chicken changes color.',
        'Add tomatoes and spices. Cook until tomatoes are soft.',
        'Add cream and simmer for 10 minutes.',
        'Garnish with fresh coriander leaves and serve hot.',
      ],
    },
    {
      id: '14',
      name: 'Chicken Tikka',
      chef: 'Chef Gulzar',
      image: require('../assets/Chicken Tikka.jpg'),
      description: 'Spicy and juicy grilled chicken tikka marinated in yogurt and spices.',
      ingredients: [
        'Chicken - 1 kg',
        'Yogurt - 1 cup',
        'Ginger-garlic paste - 2 tbsp',
        'Spices (red chili powder, turmeric, garam masala)',
        'Lemon juice - 2 tbsp',
        'Fresh coriander leaves - for garnish',
      ],
      method: [
        'Marinate chicken with yogurt, ginger-garlic paste, spices, and lemon juice for 2 hours.',
        'Grill the chicken on skewers until fully cooked.',
        'Garnish with fresh coriander leaves and serve hot.',
      ],
    },
    {
      id: '15',
      name: 'Chicken Qorma',
      chef: 'Chef Tahir Chaudhry',
      image: require('../assets/15.jpg'),
      description: 'A rich and creamy chicken curry made with yogurt and spices.',
      ingredients: [
        'Chicken - 1 kg',
        'Onions - 2 (sliced)',
        'Yogurt - 1 cup',
        'Ginger-garlic paste - 2 tbsp',
        'Spices (turmeric, red chili powder, garam masala)',
        'Fresh coriander leaves - for garnish',
      ],
      method: [
        'Fry onions until golden brown and add ginger-garlic paste.',
        'Add chicken and cook until it changes color.',
        'Add yogurt and spices. Cook until the oil separates.',
        'Garnish with fresh coriander leaves and serve hot.',
      ],
    },
    {
      id: '16',
      name: 'Chicken Nihari',
      chef: 'Chef Saadat Siddiqui',
      image: require('../assets/Chicken Nihari.jpg'),
      description: 'A slow-cooked chicken stew with a rich and spicy gravy.',
      ingredients: [
        'Chicken - 1 kg',
        'Onions - 2 (sliced)',
        'Ginger-garlic paste - 2 tbsp',
        'Spices (turmeric, red chili powder, garam masala)',
        'Wheat flour - 2 tbsp (for thickening)',
        'Fresh coriander leaves - for garnish',
      ],
      method: [
        'Cook chicken with ginger-garlic paste and spices in a pot.',
        'Add water and simmer for 2-3 hours until tender.',
        'Add wheat flour to thicken the gravy.',
        'Garnish with fresh coriander leaves and serve hot.',
      ],
    },
    {
      id: '17',
      name: 'Chicken Jalfrezi',
      chef: 'Chef Naheed Ansari',
      image: require('../assets/Chicken Jalfrezi.jpg'),
      description: 'A spicy and tangy chicken dish with bell peppers and onions.',
      ingredients: [
        'Chicken - 1 kg',
        'Bell peppers - 2 (sliced)',
        'Onions - 2 (sliced)',
        'Tomatoes - 3 (chopped)',
        'Ginger-garlic paste - 2 tbsp',
        'Spices (turmeric, red chili powder, garam masala)',
        'Fresh coriander leaves - for garnish',
      ],
      method: [
        'Fry onions until golden brown and add ginger-garlic paste.',
        'Add chicken and cook until it changes color.',
        'Add bell peppers, tomatoes, and spices. Cook until vegetables are tender.',
        'Garnish with fresh coriander leaves and serve hot.',
      ],
    },
    {
      id: '18',
      name: 'Chicken Kebab',
      chef: 'Chef Asad Latif',
      image: require('../assets/18.jpg'),
      description: 'Juicy and flavorful chicken kebabs grilled to perfection.',
      ingredients: [
        'Chicken mince - 1 kg',
        'Onions - 1 (finely chopped)',
        'Ginger-garlic paste - 2 tbsp',
        'Spices (red chili powder, garam masala)',
        'Fresh coriander leaves - for garnish',
      ],
      method: [
        'Mix chicken mince, onions, ginger-garlic paste, and spices.',
        'Shape the mixture into kebabs and grill until fully cooked.',
        'Garnish with fresh coriander leaves and serve hot.',
      ],
    },
    {
      id: '19',
      name: 'Chicken Manchurian',
      chef: 'Chef Rahat',
      image: require('../assets/19.jpg'),
      description: 'A Indo-Chinese dish with crispy chicken in a tangy sauce.',
      ingredients: [
        'Chicken - 1 kg',
        'Cornflour - 1/2 cup',
        'Soy sauce - 2 tbsp',
        'Vinegar - 1 tbsp',
        'Ginger-garlic paste - 2 tbsp',
        'Fresh coriander leaves - for garnish',
      ],
      method: [
        'Coat chicken with cornflour and deep fry until crispy.',
        'In a pan, sauté ginger-garlic paste and add soy sauce and vinegar.',
        'Add fried chicken and mix well.',
        'Garnish with fresh coriander leaves and serve hot.',
      ],
    },
  
    // Desserts
    {
      id: '20',
      name: 'Gulab Jamun',
      chef: 'Chef Shireen Anwar',
      image: require('../assets/Gulab Jamun.jpg'),
      description: 'Soft and sweet milk-based balls soaked in sugar syrup.',
      ingredients: [
        'Milk powder - 1 cup',
        'Flour - 1/4 cup',
        'Ghee - 2 tbsp',
        'Sugar - 2 cups',
        'Water - 1 cup',
        'Cardamom powder - 1/2 tsp',
      ],
      method: [
        'Mix milk powder, flour, and ghee to form a dough.',
        'Shape the dough into small balls and deep fry until golden brown.',
        'Prepare sugar syrup by boiling sugar, water, and cardamom powder.',
        'Soak the fried balls in the sugar syrup for 2 hours.',
        'Serve warm or cold.',
      ],
    },
    {
      id: '21',
      name: 'Ras Malai',
      chef: 'Chef Zubaida Tariq',
      image: require('../assets/Ras Malai.jpg'),
      description: 'Soft and creamy cheese balls soaked in sweetened milk.',
      ingredients: [
        'Paneer - 1 cup',
        'Milk - 1 liter',
        'Sugar - 1 cup',
        'Cardamom powder - 1/2 tsp',
        'Saffron strands - a few',
      ],
      method: [
        'Knead paneer into a smooth dough and shape into small balls.',
        'Boil the balls in sugar syrup until they double in size.',
        'Prepare sweetened milk with cardamom and saffron.',
        'Soak the balls in the sweetened milk for 2 hours.',
        'Serve chilled.',
      ],
    },
    {
      id: '22',
      name: 'Jalebi',
      chef: 'Chef Mehboob Khan',
      image: require('../assets/Jalebi.jpg'),
      description: 'Crispy and sweet spiral-shaped dessert soaked in sugar syrup.',
      ingredients: [
        'Flour - 1 cup',
        'Yogurt - 1/4 cup',
        'Sugar - 2 cups',
        'Water - 1 cup',
        'Saffron strands - a few',
      ],
      method: [
        'Prepare a batter with flour, yogurt, and water.',
        'Pour the batter into a piping bag and make spiral shapes in hot oil.',
        'Fry until golden brown and crispy.',
        'Prepare sugar syrup with saffron and soak the jalebis in it.',
        'Serve warm.',
      ],
    },
    {
      id: '23',
      name: 'Kheer',
      chef: 'Chef Rida Aftab',
      image: require('../assets/Kheer.jpg'),
      description: 'A creamy rice pudding made with milk, rice, and sugar.',
      ingredients: [
        'Rice - 1/2 cup',
        'Milk - 1 liter',
        'Sugar - 1 cup',
        'Cardamom powder - 1/2 tsp',
        'Almonds and pistachios - for garnish',
      ],
      method: [
        'Boil rice in milk until soft.',
        'Add sugar and cardamom powder. Simmer until thick.',
        'Garnish with chopped almonds and pistachios.',
        'Serve warm or cold.',
      ],
    },
    {
      id: '24',
      name: 'Shahi Tukray',
      chef: 'Chef Gulzar',
      image: require('../assets/Shahi Tukray.jpg'),
      description: 'A rich and creamy bread pudding made with milk and dry fruits.',
      ingredients: [
        'Bread slices - 6',
        'Milk - 1 liter',
        'Sugar - 1 cup',
        'Cardamom powder - 1/2 tsp',
        'Almonds and pistachios - for garnish',
      ],
      method: [
        'Fry bread slices in ghee until golden brown.',
        'Prepare sweetened milk with sugar and cardamom powder.',
        'Soak the fried bread slices in the sweetened milk.',
        'Garnish with chopped almonds and pistachios.',
        'Serve chilled.',
      ],
    },
  
    // Snacks and Appetizers
    {
      id: '25',
      name: 'Samosa',
      chef: 'Chef Shireen Anwar',
      image: require('../assets/Samosas.jpg'),
      description: 'Crispy and savory pastry filled with spiced potatoes and peas.',
      ingredients: [
        'Flour - 2 cups',
        'Potatoes - 3 (boiled and mashed)',
        'Peas - 1/2 cup',
        'Spices (cumin, coriander, red chili powder)',
        'Oil - for frying',
      ],
      method: [
        'Prepare dough with flour, water, and a pinch of salt.',
        'Prepare filling with mashed potatoes, peas, and spices.',
        'Shape the dough into cones and fill with the potato mixture.',
        'Deep fry until golden brown and crispy.',
        'Serve hot with chutney.',
      ],
    },
    {
      id: '26',
      name: 'Pakora',
      chef: 'Chef Mehboob Khan',
      image: require('../assets/Pakoras.jpg'),
      description: 'Crispy fritters made with gram flour and vegetables.',
      ingredients: [
        'Gram flour - 1 cup',
        'Onions - 2 (sliced)',
        'Potatoes - 2 (sliced)',
        'Spices (cumin, coriander, red chili powder)',
        'Oil - for frying',
      ],
      method: [
        'Prepare a batter with gram flour, water, and spices.',
        'Dip sliced vegetables in the batter and deep fry until crispy.',
        'Serve hot with chutney.',
      ],
    },
    {
      id: '27',
      name: 'Dahi Bhalla',
      chef: 'Chef Zubaida Tariq',
      image: require('../assets/Dahi Bhalla.jpg'),
      description: 'Soft lentil dumplings soaked in yogurt and topped with chutneys.',
      ingredients: [
        'Lentils - 1 cup',
        'Yogurt - 2 cups',
        'Tamarind chutney - 1/2 cup',
        'Mint chutney - 1/2 cup',
        'Spices (cumin, red chili powder)',
      ],
      method: [
        'Soak lentils and grind into a smooth batter.',
        'Fry small dumplings until golden brown.',
        'Soak the dumplings in water and then squeeze out excess water.',
        'Top with yogurt, chutneys, and spices.',
        'Serve chilled.',
      ],
    },
    {
      id: '28',
      name: 'Aloo Tikki',
      chef: 'Chef Rida Aftab',
      image: require('../assets/Aloo Tikki.jpg'),
      description: 'Crispy potato patties served with chutneys.',
      ingredients: [
        'Potatoes - 4 (boiled and mashed)',
        'Bread crumbs - 1/2 cup',
        'Spices (cumin, coriander, red chili powder)',
        'Oil - for frying',
      ],
      method: [
        'Mix mashed potatoes, bread crumbs, and spices.',
        'Shape into small patties and shallow fry until golden brown.',
        'Serve hot with chutney.',
      ],
    },
    {
      id: '29',
      name: 'Kachori',
      chef: 'Chef Gulzar',
      image: require('../assets/Kachori.jpg'),
      description: 'Crispy and flaky pastry filled with spiced lentils.',
      ingredients: [
        'Flour - 2 cups',
        'Lentils - 1/2 cup',
        'Spices (cumin, coriander, red chili powder)',
        'Oil - for frying',
      ],
      method: [
        'Prepare dough with flour, water, and a pinch of salt.',
        'Prepare filling with cooked lentils and spices.',
        'Shape the dough into small discs and fill with the lentil mixture.',
        'Deep fry until golden brown and crispy.',
        'Serve hot with chutney.',
      ],
    },
    {
      id: '30',
      name: 'Chicken Patties',
      chef: 'Chef Tahir Chaudhry',
      image: require('../assets/Chicken Patties.jpg'),
      description: 'Flaky pastry filled with spiced chicken filling.',
      ingredients: [
        'Flour - 2 cups',
        'Chicken - 1/2 kg (cooked and shredded)',
        'Spices (cumin, coriander, red chili powder)',
        'Oil - for frying',
      ],
      method: [
        'Prepare dough with flour, water, and a pinch of salt.',
        'Prepare filling with shredded chicken and spices.',
        'Shape the dough into small discs and fill with the chicken mixture.',
        'Bake or fry until golden brown.',
        'Serve hot.',
      ],
    },
    {
      id: '31',
      name: 'Spring Rolls',
      chef: 'Chef Naheed Ansari',
      image: require('../assets/Spring Roll.webp'),
      description: 'Crispy rolls filled with vegetables and noodles.',
      ingredients: [
        'Spring roll wrappers - 10',
        'Cabbage - 1 cup (shredded)',
        'Carrots - 1 cup (shredded)',
        'Noodles - 1 cup (cooked)',
        'Oil - for frying',
      ],
      method: [
        'Prepare filling with shredded vegetables and noodles.',
        'Wrap the filling in spring roll wrappers.',
        'Deep fry until golden brown and crispy.',
        'Serve hot with dipping sauce.',
      ],
    },
    {
      id: '32',
      name: 'Chapli Kebab',
      chef: 'Chef Asad Latif',
      image: require('../assets/Chapli Kebab.jpg'),
      description: 'Spicy and flavorful minced meat kebabs.',
      ingredients: [
        'Beef mince - 1 kg',
        'Onions - 1 (finely chopped)',
        'Tomatoes - 2 (finely chopped)',
        'Spices (cumin, coriander, red chili powder)',
        'Oil - for frying',
      ],
      method: [
        'Mix beef mince, onions, tomatoes, and spices.',
        'Shape into flat patties and shallow fry until cooked.',
        'Serve hot with naan or salad.',
      ],
    },
    {
      id: '33',
      name: 'Shami Kebab',
      chef: 'Chef Rahat',
      image: require('../assets/Shami Kebab.jpg'),
      description: 'Soft and spicy lentil and meat kebabs.',
      ingredients: [
        'Beef - 1/2 kg',
        'Lentils - 1/2 cup',
        'Spices (cumin, coriander, red chili powder)',
        'Oil - for frying',
      ],
      method: [
        'Cook beef and lentils together until tender.',
        'Grind into a smooth mixture and add spices.',
        'Shape into small patties and shallow fry until golden brown.',
        'Serve hot with chutney.',
      ],
    },
    {
      id: '34',
      name: 'Gol Gappay',
      chef: 'Chef Saadat Siddiqui',
      image: require('../assets/Gol Gappay.jpg'),
      description: 'Crispy hollow puris filled with spicy water and chutneys.',
      ingredients: [
        'Flour - 1 cup',
        'Potatoes - 2 (boiled and mashed)',
        'Tamarind chutney - 1/2 cup',
        'Mint water - 1/2 cup',
        'Spices (cumin, red chili powder)',
      ],
      method: [
        'Prepare dough with flour and water.',
        'Shape into small puris and deep fry until crispy.',
        'Fill the puris with mashed potatoes, chutneys, and mint water.',
        'Serve immediately.',
      ],
    },
  ];
  
  export default recipesData;